spring:
  application:
    name: fnet

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

jwt:
  secret: 304f61435aab13b01e19eefae55493f57c60202330b1853d231032a8dfab8adf # 변경하기!!!!

api:
  prefix: '/api'

password:
  init: 'tb2025'